CREATE TABLE IF NOT EXISTS auth.users (
                            id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            username VARCHAR(20) NOT NULL UNIQUE,
                            password VARCHAR(60) NOT NULL,
                            role VARCHAR(20) NOT NULL
);