spring:
  config:
    import: "optional:file:.env.local[.properties]"



  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        default_schema: auth
    hibernate:
      ddl-auto: update

  flyway:
    schemas: auth
    default-schema: auth
    table: flyway_schema_history
    baseline-on-migrate: true
    enabled: true
    baseline-version: 0

  mvc:
    hidden-method:
      filter:
        enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB
    cookie:
      same-site: lax
      secure: false
      name: SESSION

  session:
    timeout: 30m
    redis:
      flush-mode: on_save

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      
app:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}

  url:
    nginx: ${NGINX_URL}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.session: DEBUG
    org.springframework.data.redis: DEBUG