CREATE SCHEMA IF NOT EXISTS auth;
CREATE TABLE IF NOT EXISTS auth.users
(
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(20) NOT NULL CHECK (username != '') UNIQUE,
    password VARCHAR(60) NOT NULL CHECK (password != ''),
    role     VARCHAR(20) NOT NULL CHECK (role != '')
);
INSERT INTO auth.users (username, password, role)
VALUES ('user', '$2a$05$gA.g4X3PAGub2S7RW5G6bu.VB6/Y9OvrKh.4c744wJKfM7F6zriFC', 'USER');