CREATE SCHEMA IF NOT EXISTS auth;
CREATE TABLE IF NOT EXISTS auth.users
(
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(20) NOT NULL CHECK (username != '') UNIQUE,
    password VARCHAR(60) NOT NULL CHECK (password != ''),
    role     VARCHAR(20) NOT NULL CHECK (role != '')
);